steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase', './dockerfiles/firebase']
  - name: 'node:19.3.0'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:19.3.0'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args: ['use', '${_FIREBASE_PROJECT_ID}', '--token', '${_FIREBASE_TOKEN}']
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args: ['target:apply', 'hosting', 'devlog-4ecc0', 'devlog-4ecc0', '--token', '${_FIREBASE_TOKEN}']
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args: ['deploy', '--token', '${_FIREBASE_TOKEN}', '--only', 'hosting:devlog-4ecc0']
timeout: 1200s
